# Generated by Django 4.2.8 on 2023-12-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='low_test_mark',
            field=models.SmallIntegerField(default=2, max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='no_of_samples',
            field=models.SmallIntegerField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='product',
            name='upper_test_mark',
            field=models.SmallIntegerField(default=2, max_length=2),
        ),
    ]
