# Generated by Django 4.2.8 on 2023-12-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_product_complete_product_low_test_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='low_test_mark',
            field=models.SmallIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_of_samples',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='upper_test_mark',
            field=models.SmallIntegerField(default=2),
        ),
    ]
