# Generated by Django 4.2.8 on 2023-12-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_low_test_mark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='p_val',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='q_val',
            field=models.CharField(blank=True, default='___', max_length=4, null=True),
        ),
    ]
