# Generated by Django 4.2.8 on 2023-12-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_exercise_p_val_alter_exercise_q_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='table',
            field=models.SmallIntegerField(default=0),
        ),
    ]
