# Generated by Django 4.2.8 on 2023-12-30 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='o_val',
            field=models.CharField(blank=True, default='___', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='webapp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
    ]
